In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [43]:
train_df = pd.read_csv('./loan_prediction/train_u6lujuX_CVtuZ9i.csv')
test_df = pd.read_csv('./loan_prediction/test_Y3wMUE5_7gLdaTN.csv')

In [11]:
train_df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [12]:
train_df.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [13]:
train_df.isna()

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0      False   False    False       False      False          False   
1      False   False    False       False      False          False   
2      False   False    False       False      False          False   
3      False   False    False       False      False          False   
4      False   False    False       False      False          False   
..       ...     ...      ...         ...        ...            ...   
609    False   False    False       False      False          False   
610    False   False    False       False      False          False   
611    False   False    False       False      False          False   
612    False   False    False       False      False          False   
613    False   False    False       False      False          False   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0              False              False        True             False   
1              False              False       False             False   
2              False              False       False             False   
3              False              False       False             False   
4              False              False       False             False   
..               ...                ...         ...               ...   
609            False              False       False             False   
610            False              False       False             False   
611            False              False       False             False   
612            False              False       False             False   
613            False              False       False             False   

     Credit_History  Property_Area  Loan_Status  
0             False          False        False  
1             False          False        False  
2             False          False        False  
3             False          False        False  
4             False          False        False  
..              ...            ...          ...  
609           False          False        False  
610           False          False        False  
611           False          False        False  
612           False          False        False  
613           False          False        False  

[614 rows x 13 columns]

In [14]:
train_df.shape

(614, 13)

In [15]:
train_df.tail()

Loan_ID  Gender Married Dependents Education Self_Employed  \
609  LP002978  Female      No          0  Graduate            No   
610  LP002979    Male     Yes         3+  Graduate            No   
611  LP002983    Male     Yes          1  Graduate            No   
612  LP002984    Male     Yes          2  Graduate            No   
613  LP002990  Female      No          0  Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N

In [16]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [19]:
test_df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001015   Male     Yes          0      Graduate            No   
1  LP001022   Male     Yes          1      Graduate            No   
2  LP001031   Male     Yes          2      Graduate            No   
3  LP001035   Male     Yes          2      Graduate            No   
4  LP001051   Male      No          0  Not Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5720                  0       110.0             360.0   
1             3076               1500       126.0             360.0   
2             5000               1800       208.0             360.0   
3             2340               2546       100.0             360.0   
4             3276                  0        78.0             360.0   

   Credit_History Property_Area  
0             1.0         Urban  
1             1.0         Urban  
2             1.0         Urban  
3             NaN         Urban  
4             1.0         Urban

In [44]:
#setting axis as 1 since we are dropping the column Loan_ID from the data
#inplace is set to True to do inplace than as a copy
train_df.drop(labels='Loan_ID',axis=1,inplace=True)

In [46]:
train_df

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0      Male      No          0      Graduate            No             5849   
1      Male     Yes          1      Graduate            No             4583   
2      Male     Yes          0      Graduate           Yes             3000   
3      Male     Yes          0  Not Graduate            No             2583   
4      Male      No          0      Graduate            No             6000   
..      ...     ...        ...           ...           ...              ...   
609  Female      No          0      Graduate            No             2900   
610    Male     Yes         3+      Graduate            No             4106   
611    Male     Yes          1      Graduate            No             8072   
612    Male     Yes          2      Graduate            No             7583   
613  Female      No          0      Graduate           Yes             4583   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0.0         NaN             360.0             1.0   
1               1508.0       128.0             360.0             1.0   
2                  0.0        66.0             360.0             1.0   
3               2358.0       120.0             360.0             1.0   
4                  0.0       141.0             360.0             1.0   
..                 ...         ...               ...             ...   
609                0.0        71.0             360.0             1.0   
610                0.0        40.0             180.0             1.0   
611              240.0       253.0             360.0             1.0   
612                0.0       187.0             360.0             1.0   
613                0.0       133.0             360.0             0.0   

    Property_Area Loan_Status  
0           Urban           Y  
1           Rural           N  
2           Urban           Y  
3           Urban           Y  
4           Urban           Y  
..            ...         ...  
609         Rural           Y  
610         Rural           Y  
611         Urban           Y  
612         Urban           Y  
613     Semiurban           N  

[614 rows x 12 columns]

In [47]:
train_df.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [53]:
#we are going to pick only the object type columns alone
column_objects = [col for col in train_df.columns if train_df[col].dtypes == 'object']

In [54]:
column_objects

['Gender',
 'Married',
 'Dependents',
 'Education',
 'Self_Employed',
 'Property_Area',
 'Loan_Status']

In [55]:
train_df.isna().sum()

Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [60]:
#calculating total missing values in train_df dataframe for each columns
# another .sum() is added to add the number of missing values
total_missing_values = train_df.isna().sum().sum()

In [61]:
total_missing_values

149

In [63]:
np.product(train_df.shape)

7368

In [64]:
#calculating total missing values percentage
total_percentage = total_missing_values/np.product(train_df.shape) * 100

In [66]:
#we have 2 % data is missing in the train_df dataset
total_percentage

2.022258414766558

In [91]:
#finding all the null value columns so that we can fill it with mean value
na_col = train_df.columns[train_df.isna().any()].to_list()

In [117]:
na_obj_col = [col for col in train_df[na_col].columns if train_df[col].dtypes == 'object']
na_flt_col = [col for col in train_df[na_col].columns if train_df[col].dtypes == 'float64']

In [130]:
mode = train_df.mode()
#we can use the manual method for median or we can use the imputer method
#median = train_df[na_flt_col].median()

In [131]:
mode

Gender Married Dependents Education Self_Employed  ApplicantIncome  \
0   Male     Yes          0  Graduate            No             2500   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0  146.412162             360.0             1.0   

  Property_Area Loan_Status  
0     Semiurban           Y

In [123]:
#we used simple imputer function here to fill the na values with mean only for float columns
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(train_df[na_flt_col])
train_df[na_flt_col] = imputer.transform(train_df[na_flt_col])

In [133]:
# we used manual fixing for the object columns using the mode functionality
train_df[na_obj_col] = train_df[na_obj_col].fillna(train_df.mode().iloc[0])

In [137]:
#now we have 0 null values
train_df.isna().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [138]:
#now we are going to encode the object columns with label encoder
column_objects

['Gender',
 'Married',
 'Dependents',
 'Education',
 'Self_Employed',
 'Property_Area',
 'Loan_Status']

In [139]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
train_df[column_objects] = train_df[column_objects].apply(labelencoder.fit_transform)

In [140]:
#data after we have encoded them.
train_df

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0         1        0           0          0              0             5849   
1         1        1           1          0              0             4583   
2         1        1           0          0              1             3000   
3         1        1           0          1              0             2583   
4         1        0           0          0              0             6000   
..      ...      ...         ...        ...            ...              ...   
609       0        0           0          0              0             2900   
610       1        1           3          0              0             4106   
611       1        1           1          0              0             8072   
612       1        1           2          0              0             7583   
613       0        0           0          0              1             4583   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0.0  146.412162             360.0             1.0   
1               1508.0  128.000000             360.0             1.0   
2                  0.0   66.000000             360.0             1.0   
3               2358.0  120.000000             360.0             1.0   
4                  0.0  141.000000             360.0             1.0   
..                 ...         ...               ...             ...   
609                0.0   71.000000             360.0             1.0   
610                0.0   40.000000             180.0             1.0   
611              240.0  253.000000             360.0             1.0   
612                0.0  187.000000             360.0             1.0   
613                0.0  133.000000             360.0             0.0   

     Property_Area  Loan_Status  
0                2            1  
1                0            0  
2                2            1  
3                2            1  
4                2            1  
..             ...          ...  
609              0            1  
610              0            1  
611              2            1  
612              2            1  
613              1            0  

[614 rows x 12 columns]

In [198]:
#all we have done is data preprocessing
#now we are going to split them into X and y
# here y is the loan status and the remaining columns are features. So the features will be in X
X = train_df.iloc[:,:-1].values
y = train_df.iloc[:,-1].values

In [200]:
print(X)

[[  1.   0.   0. ... 360.   1.   2.]
 [  1.   1.   1. ... 360.   1.   0.]
 [  1.   1.   0. ... 360.   1.   2.]
 ...
 [  1.   1.   1. ... 360.   1.   2.]
 [  1.   1.   2. ... 360.   1.   2.]
 [  0.   0.   0. ... 360.   0.   1.]]


In [201]:
print(y)

[1 0 1 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 1 0 1 0 0 0 1 1 1 0 1 0 0 0 1 0 1 0
 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 1 1 0 0 0 0 0 1 1 0 1 1 1 0
 1 0 0 0 0 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1 0 0 0 1 1 1 1 1 1 1
 0 1 0 1 0 0 1 1 1 1 1 1 1 0 0 1 1 1 0 1 0 1 1 1 0 1 0 1 1 0 1 0 0 0 1 0 1
 1 0 1 1 1 1 0 0 1 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 0 0 0 1 1 1 1 0 1 0 1 0 1
 1 1 1 0 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 0 1 1 1 1 0 0 1 1 0 1 0 0 0
 0 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 1 0 1 1
 1 1 0 0 0 1 1 1 1 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1
 1 1 1 1 1 0 1 0 0 1 1 1 1 0 1 1 1 1 0 1 0 1 1 1 0 0 1 0 1 1 1 1 0 0 0 1 0
 1 1 1 0 1 1 1 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 0 1 1 0 0 0 1 1 0 1 1
 1 0 0 0 1 0 1 0 1 0 0 1 1 1 0 1 0 1 1 0 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1
 1 1 1 0 0 0 0 1 0 1 1 1 1 0 1 0 1 1 1 1 0 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 1
 1 1 1 1 1 0 0 1 0 1 1 1 

In [202]:
#now we have split the data into X and y, we can go ahead and split them using train test split and train the models
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33,random_state=0)

In [203]:
#we are doing feature scaling here. this increases models performance and accuracy
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [204]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [205]:
X_train

array([[ 0.45697213,  0.68017163,  1.17320446, ..., -2.63882236,
        -2.33219141,  1.18562574],
       [ 0.45697213,  0.68017163, -0.78292955, ...,  0.28792764,
         0.46791683, -1.35235436],
       [ 0.45697213,  0.68017163,  2.15127146, ...,  0.28792764,
         0.46791683, -1.35235436],
       ...,
       [ 0.45697213,  0.68017163,  2.15127146, ...,  0.28792764,
         0.46791683, -0.08336431],
       [ 0.45697213,  0.68017163, -0.78292955, ...,  0.28792764,
         0.46791683,  1.18562574],
       [-2.18831725,  0.68017163, -0.78292955, ...,  0.28792764,
         0.46791683, -0.08336431]])

In [206]:
X_test

array([[ 0.45697213, -1.47021715, -0.78292955, ...,  0.28792764,
         0.46791683, -0.08336431],
       [-2.18831725, -1.47021715, -0.78292955, ...,  0.28792764,
         0.46791683, -0.08336431],
       [ 0.45697213,  0.68017163, -0.78292955, ...,  0.28792764,
         0.46791683,  1.18562574],
       ...,
       [ 0.45697213,  0.68017163, -0.78292955, ...,  0.28792764,
         0.46791683, -1.35235436],
       [ 0.45697213, -1.47021715, -0.78292955, ...,  0.28792764,
         0.46791683,  1.18562574],
       [ 0.45697213,  0.68017163, -0.78292955, ..., -2.63882236,
         0.46791683, -1.35235436]])

In [207]:
#this is done to print all the parameters of the classifier
from sklearn import set_config
set_config(print_changed_only=False)

In [208]:
# we are using Kernel svm for this classification problem
from sklearn.svm import SVC
classifier = SVC(kernel='rbf',random_state=0)
classifier.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [225]:
#we are going to predict the values for the X_test data
y_pred_svm = classifier.predict(X_test)

In [229]:
#print the predicted and original values below
print(np.concatenate((y_pred_svm.reshape(len(y_pred_svm),1),y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]

In [227]:
#calculation the accuracy scores, confusion matrix and classification report
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
confusion_mat_ksvm = confusion_matrix(y_test,y_pred_svm)
acc_score_ksvm = accuracy_score(y_test,y_pred_svm)
class_report_ksvm = classification_report(y_test,y_pred_svm)

In [228]:
print('Confusion Matrix')
print(f"{confusion_mat_ksvm}\n")
print(f'Accuracy score: {acc_score_ksvm}\n')
print('Classification report:')
print(class_report_ksvm)

Confusion Matrix
[[ 25  33]
 [  2 143]]

Accuracy score: 0.8275862068965517

Classification report:
              precision    recall  f1-score   support

           0       0.93      0.43      0.59        58
           1       0.81      0.99      0.89       145

    accuracy                           0.83       203
   macro avg       0.87      0.71      0.74       203
weighted avg       0.84      0.83      0.80       203



In [250]:
#lets try out Randomforest classifier on the same dataset to get the accuracy score
#random state is not needed. you can use it if you want to see the same results as mine
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=2500,criterion='entropy',random_state=0)
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=2500,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [251]:
y_pred_rbc = rfc.predict(X_test)
print(np.concatenate((y_pred_rbc.reshape(len(y_pred_rbc),1),y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [0 1]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]

In [252]:
confusion_mat_rfc = confusion_matrix(y_test,y_pred_rbc)
acc_score_rfc = accuracy_score(y_test,y_pred_rbc)
class_report_rfc = classification_report(y_test,y_pred_rbc)

In [254]:
print('Confusion Matrix')
print(f"{confusion_mat_rfc}\n")
print(f'Accuracy score: {acc_score_rfc}\n')
print('Classification report:')
print(class_report_rfc)

Confusion Matrix
[[ 26  32]
 [  7 138]]

Accuracy score: 0.8078817733990148

Classification report:
              precision    recall  f1-score   support

           0       0.79      0.45      0.57        58
           1       0.81      0.95      0.88       145

    accuracy                           0.81       203
   macro avg       0.80      0.70      0.72       203
weighted avg       0.80      0.81      0.79       203



In [292]:
test_df = pd.read_csv('./loan_prediction/test_Y3wMUE5_7gLdaTN.csv')

In [293]:
test_df.drop(labels='Loan_ID',axis=1,inplace=True) 

In [294]:
#lets do this on our test data
column_objects_test = [col for col in test_df.columns if test_df[col].dtypes == 'object']

In [295]:
column_objects_test

['Gender',
 'Married',
 'Dependents',
 'Education',
 'Self_Employed',
 'Property_Area']

In [296]:
test_df.isna().sum()

Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [297]:
na_col_test = test_df.columns[test_df.isna().any()].to_list()
na_obj_col_test = [col for col in test_df[na_col_test].columns if test_df[col].dtypes == 'object']
na_flt_col_test = [col for col in test_df[na_col_test].columns if test_df[col].dtypes == 'float64']

In [298]:
imputer.fit(test_df[na_flt_col_test])
test_df[na_flt_col_test] = imputer.transform(test_df[na_flt_col_test])
test_df[na_obj_col_test] = test_df[na_obj_col_test].fillna(test_df.mode().iloc[0])

In [299]:
test_df.isna().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [301]:
test_df[column_objects_test] = test_df[column_objects_test].apply(labelencoder.fit_transform)

In [302]:
y_test_pred = rfc.predict(test_df)

In [327]:
print(y_test_pred)

[1 0 0 0 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0 1 0
 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 1 0 1 0 1 1 1 0 1 1 0 0
 0 0 0 1 0 1 0 1 1 1 1 0 0 1 0 1 0 1 0 0 0 1 0 0 1 1 1 1 1 1 0 0 0 1 1 0 1
 1 1 0 0 0 0 0 0 0 1 0 0 0 1 1 1 1 1 0 0 1 0 1 1 1 1 0 0 1 1 0 0 1 1 1 1 1
 0 1 0 0 1 1 1 0 0 0 0 1 0 1 1 1 0 1 0 0 0 1 1 1 1 0 0 0 0 1 1 1 0 0 1 0 0
 1 0 1 1 0 1 1 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0
 1 1 1 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 1 0 0 1 1 1 0 1 1 0 0 1 1 0 0
 0 0 0 0 1 0 0 1 0 0 1 0 0 1 0 1 0 1 1 0 1 0 1 1 1 0 1 0 0 1 0 0 0 1 0 0 1
 1 1 1 1 1 1 1 0 0 0 1 1 1 0 1 0 0 1 1 0 1 0 1 0 0 0 1 0 1 0 0 0 0 0 1 1 0
 1 0 1 0 0 0 0 0 0 1 1 1 1 0 1 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1]


In [356]:
#reconverting it to the original values
y_test_pred = np.array(['Y' if item==1 else 'N' for item in y_test_pred])

In [355]:
type(y_test_preddd)

numpy.ndarray

In [357]:
#adding the predictions back to the test_dataframe
test_df['Loan_Status'] = y_test_pred

In [358]:
test_df.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        1           0          0              0             5720   
1       1        1           1          0              0             3076   
2       1        1           2          0              0             5000   
3       1        1           2          0              0             2340   
4       1        0           0          1              0             3276   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0       110.0             360.0        1.000000   
1               1500       126.0             360.0        1.000000   
2               1800       208.0             360.0        1.000000   
3               2546       100.0             360.0        0.825444   
4                  0        78.0             360.0        1.000000   

   Property_Area Loan_Status  
0              2           Y  
1              2           N  
2              2           N  
3              2           N  
4              2           Y